# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 204452685424cfdf7c9538a392362a499201cfaa2660938da025d3f77416835f881c38da6903da09a27287aef63bb4fae356f995cc242b5ff08a0a534596075f

test:
  secret_key_base: f7c1dc34f6d11c5b329f17517557150defd3a956a256c9679934b284ff64159b03bdaf8e85ca94dc25a9578afaec52cceb916c5dbf4c917c608f9a4ff2fe33d3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
